### ISSUE TITLE
Wrong file size, missing tracker seeds/leechs for files larger than 2GB

### ISSUE THREAD

**Issue by ihabovich** [atmoner/Bittytorrent#12]
I just noticed that every single torrent that have files of total size large than 2GB, show exactly 2GB size  while both seeds and leechs = 0.

**Comment by atmoner** [comment]
It is a chain reaction! The scrape does not work because it has not the right size of the contents of the torrent file!
If that seems odd to me is that the size is correctly displayed when you upload (see picture)

![bitetosize](https://cloud.githubusercontent.com/assets/1071490/9268243/fa945f0e-425c-11e5-92b2-17a1741c2ea6.png)

Today, I use the class bdecode in the file upload.form.php 
and I record the bytes in database but I think we should check directly into the torrent file metadata to calculate the exact size!

I will quickly settle this problem

**Comment by ihabovich** [comment]
Indeed size correctly displayed when upload. Thanks for your dedication, waiting for the fix :)

**Comment by atmoner** [comment]
The problem is the restriction of the integer in the "size" field of the table torrents.
Just run this query:
```sql
ALTER TABLE `torrents` CHANGE `size` `size` BIGINT( 11 ) NOT NULL ;
```
Fix commit: 1c19abe857cdf66e8c5965b6e22cebef7b14f7ea :dart: 

Now, scrape work prefectly :+1: 
![bitetosize](https://cloud.githubusercontent.com/assets/1071490/9268920/2540d30c-4264-11e5-944c-92466d4e674f.png)

**Comment by atmoner** [comment]
@ihabovich it work perfect! try it on http://demo.bittytorrent.com/  
And check this torrent: http://demo.bittytorrent.com/torrent-detail/3015/photoshop-week-2015

**Comment by ihabovich** [comment]
I can`t upload on demo link since I got no permission. The torrent page seem have right size but wrong  seeds/leechs number!

**Comment by atmoner** [comment]
lol! simple scrape and it's ok =) 
Visitors & members can upload now ;)

**Comment by ihabovich** [comment]
Here what I get on http://demo.bittytorrent.com/

![upload torrent demo bittytorrent](https://cloud.githubusercontent.com/assets/13511260/9272099/7c90de66-427f-11e5-8c13-d7f670d84c75.png)

and the detail page:

![detail torrent demo bittytorrent](https://cloud.githubusercontent.com/assets/13511260/9272137/b4e0cb6e-427f-11e5-85fd-f91b0816d89d.png)

**Comment by atmoner** [comment]
Strange! On my localhost it work perfectly = or > 2gb
My local host
![localhost](https://cloud.githubusercontent.com/assets/1071490/9272647/eedb3cdc-4284-11e5-8278-3801fa3e5a2d.png)

And for the same torrent on my hosting:
![demo](https://cloud.githubusercontent.com/assets/1071490/9272645/ec4d8416-4284-11e5-8566-046ccba699f8.png)

Your operating system run on 32 or 64bits?

**Comment by ihabovich** [comment]
64bit WIndows

**Comment by atmoner** [comment]
the problem come from the server configuration and / or machines ....

**Comment by ihabovich** [comment]
It seem to be get fixed, not by myself doing anything. Could be something with server as you mentioned. cheers :+1:

**Comment by atmoner** [comment]
If you have another problem, does not hesitate to use the forum: http://forum.bittytorrent.com/
